### ISSUE TITLE
Some Tests are platform specific?

### ISSUE THREAD

**Issue by SentryMan** [byronka/minum#13]
I'm running windows 11, and it seems I'm unable to successfully run the master branch tests via `mvn clean package`. Is there anything required to build locally? 

It seems also that there are test failures running on Ubuntu Github actions steps as well.

**Comment by byronka** [comment]
Can you try running with Cygwin? i always run the tests on that, with `make test`

**Comment by byronka** [comment]
also, can you provide here what’s the error you’re seeing?

**Comment by SentryMan** [comment]
![image](https://github.com/user-attachments/assets/26427371-d419-4b5e-b4d1-34343f1a03e6)
![image](https://github.com/user-attachments/assets/67f7147c-973f-420d-af6a-5f0b321b6cc2)

**Comment by byronka** [comment]
wow.  I had no idea tests would fail.  Is it just those two each time? Is it consistent?

**Comment by SentryMan** [comment]
Consistently with these two

**Comment by byronka** [comment]
And what version of Java are you on? With as much specificity as possible please.

**Comment by SentryMan** [comment]
![image](https://github.com/user-attachments/assets/37db4a96-1fea-420e-a846-5fd598ec22dc)

**Comment by byronka** [comment]
First of all, I am grateful to you for finding these issues.  Thank you!

Regarding the test failures:

The issues you are seeing when you test locally:
------------------------------------------------

The problem is that two of the test files (specifically the file "gettysburg_address.txt" and "expected_stock_output_parsed.txt") are being checked out with CRLF line endings, which happens when using the default Windows Git configuration.

I'm documenting the preferred operating system environments - Linux, Mac, Cygwin on Windows.  Line endings are an endless source of pain with Git.  I thought I had fixed this with the appropriate `.gitattributes` configuration, but apparently not for Windows Git.


The issues in the github workflow action:
-----------------------------------------

Very weird, that I never saw this before, because the issue is file name capitalization.  The test in question, "test_readStaticFile_IOException", tries to read a file, "foo", from the test directory.  Note the capitalization - all lowercase.  The actual file in src/test/webapp/static/static is named "Foo" - uppercase F.  This should have failed on Mac.  On Cygwin, maybe it wouldn't have failed because Windows filenames are case insensitive.  Good to have found it.  Here is the diff that fixes it:

```
@@ -140,7 +140,7 @@ public class WebFrameworkTests {
     @Test
     public void test_readStaticFile_IOException() {
         webFramework = new WebFramework(context, default_zdt, throwingFileReader);
-        IResponse response = webFramework.readStaticFile("foo", defaultHeaders);
+        IResponse response = webFramework.readStaticFile("Foo", defaultHeaders);

         assertEquals(response.getStatusCode(), CODE_400_BAD_REQUEST);
     }
```

I'm going to add some documentation to describe the preferred development environments.  Try installing Cygwin and cloning the project again, that worked for me on Windows 11.

**Comment by SentryMan** [comment]
I pulled the changes from master and running on cygwin doesn't resolve
![image](https://github.com/user-attachments/assets/b8cf698a-7995-40ca-9306-0acf1cd41746)

**Comment by byronka** [comment]
Not quite sure what you mean by changes from master.  I haven't changed anything on master, yet.  You can resolve the test failures locally by switching the aforementioned files to use lf for eol instead of crlf, or you can clone the repo again using cygwin, and make sure to read up on [line endings on stackoverflow](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings)

**Comment by SentryMan** [comment]
that seems to have worked
