### ISSUE TITLE
Dependency injection recommendation?

### ISSUE THREAD

**Issue by jcrben** [byronka/minum#9]
Do you have a recommendation for how to handle dependency injection? 

Probably the simplest way to swap out dependencies for tests is to use the Service Locator pattern.

I glanced at the handbook (https://github.com/byronka/minum/blob/master/docs/development_handbook.md#testing) and didn't see anything about this topic.

**Comment by byronka** [comment]
Would you mind explaining a bit further what you mean here, and what you are trying to achieve? 

I intentionally avoided including service locators / inversion of control containers because, in my opinion, their added complexity costs more than the benefit they provide.

For the majority of my dependency injection needs, I'm passing in instantiated objects.  In certain rare cases, such as SocketWrapper, it was important to be able to mock its abilities to do some testing, so I was forced to add an interface for it, and then I could create a "FakeSocketWrapper".

**Comment by jcrben** [comment]
I think you probably get a sense for what I want - the standard stuff you get from DI such as easier swapping out components during testing.

It sounds like you just pass in objects, which is sometimes called the poor man's dependency injection. I don't mean to use that pejoratively - it's still pretty good and obviously very explicit. But it can be tricky / tedious threading something through to where it needs to be.

One area where I've used dependency injection outside of testing is to run parallel implementations for feature flags. It cuts down on the number of if conditions. John Carmack wrote about this practice [see this](http://sevangelatos.com/john-carmack-on-parallel-implementations/). I originally encountered this article on stackoverflow which has some discussion: https://news.ycombinator.com/item?id=20582634

In any case, I think you've answered my question, thanks - feel free to close this 😄

**Comment by byronka** [comment]
Fair points, and thank you for the links - it's solid stuff.  I will admit, I've probably developed an allergy to IOC containers because of their (just in my opinion) complex setup and the pain I encountered when trying to debug.  I've certainly heard a lot of people sing their praises.  I will admit that my bias is for making things as boring simple as possible for the intent of making debugging easier, and generally having fewer moving pieces.  I could be wrong about this - I often am.
